---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-backup
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: minio-backup-secret
    creationPolicy: Owner
    template:
      data:
        MINIO_ROOT_USER: "{{ .MINIO_ROOT_USER }}"
        MINIO_ROOT_PASSWORD: "{{ .MINIO_ROOT_PASSWORD }}"
  dataFrom:
    - extract:
        key: minio-backup
