---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homebox
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homebox-secret
    creationPolicy: Owner
    template:
      data:
        HBOX_AUTH_API_KEY_PEPPER: "{{ .AUTH_API_KEY_PEPPER }}"
  dataFrom:
    - extract:
        key: homebox
