# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:4zetlux3uewH0yxTKjtXb1Zz7P6wbqttaE0tQm1Rp/VpXxBf3ttZayr26jTbALGhEtbvqDaaXXSZSRnMlSHSM2nzxv2buJ/fuq96MTUPMEZw/alhGFIKEKr2UDdZ0qH0jgf0WqUku3XRXEWuptBDzDFoR0xzhlqA3fjMYKdbsAbTfvvkTOo/h30uV8caXBL7Nzv1UpPHnhJNDuTjfg3PogcleF0uw1T22GaQ4RH+Vw==,iv:3EbaJ8s1627hM0rZZBZ3cjQj5SkG6I+DOulUaJAbuQU=,tag:A6CH43nD/NWKG1G6Gl1KDg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10t30tc0pp7zqm950zmuk2pzhl2tlx4sy0r4y39p4nr38vm80jf8q52urda
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueE1POEJRTzVrK2tBODBD
        aVpob05qMzBFNjZVbEIzUlJKQVhucHp2b2tBCm9Vc1N1aTdUQkFMY1dyVjZhS1pq
        enNBQ2UzeTZEaVJmZzNnQ3VDV051ZlUKLS0tIG5uWjZEVFdRMURVRW1uZFMyUXE0
        bGROb05OOXpkWFJpNDgxZTVMcnNSZkEK0Srt/QT/A6dye36ZhKTuyh3A2NJwlQMA
        3KvzD1MIzmpX4bG4+IsFoetNUKY5kUM86UUh9DAlbI7ORa+Dcy4OGw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-20T18:57:19Z"
  mac: ENC[AES256_GCM,data:WZ/SfCYkKs/HnJGtWP+9aMhh+ycs9Fiy83mIazYexs2F2d8QhyOTv63cut5g3hnBA/L3hwoCnmxZdegfUlLJrMlTZpa3WdmNPomJHZMtJG1kTfiiv2ZZ9pJQ1X3r4UaG7y+49BhRpW9ub3GsgJzrEpfHayd7CPF5AxV69Hd0yz0=,iv:/dpzvfK4nqSKP6n6Jp+j6OqEcH342sCNyExUa5YNc+0=,tag:h1z9+H3mawuxhes82VvZig==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
