kind: ENC[AES256_GCM,data:Ay64ffKV,iv:naZO2gl/DueEoUwmGV3SSd52XPL4kfDl6t1B2d7Hl20=,tag:V680Gsl6zoBmIT5VJ6MISg==,type:str]
ansible_user: ENC[AES256_GCM,data:qqLZhg==,iv:6NmdXSm9kkRklAXbgIYjoB6yoXuNCNNu5RDqhxx60gk=,tag:cGjhGndCxqhJh2q4LsM9mw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:zKe2lEpXHnE=,iv:7mhQFc/8DWz34dfoC4M9uy+wZ/TbilUF3TxXkjztGYo=,tag:X5QqKq+IuNnsDdBAzWz0dw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekglqwyv6f4pq359thxuzaxvlu932wzlfs223afputtnxlvv949spkxy6c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHb0dXOGRxWFE3OWNSaG93
            QmlpUHNCZjNjY1NpWVNjS2ZzeUg5VVpRVm1zClVFWHdIMm1oZ2p3WEZKMEFSRVNH
            YW02K0JtVjVnVjFlZkVhckNRVElFcmsKLS0tIG9UbTJ2SXQ1NTcwd3E2U3MvaTFm
            RnhJU1BJWW1YNjhnQXNMdUZXZWdBVWcKXkWiAc4/X7w0tvuuUk39HKwkpwTzBsdN
            iS5C9RA/XrXzyFrHGrGRClY8pE0Ll4HZSYpTg0mPpKoc41k1g6BRxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-02T09:19:54Z"
    mac: ENC[AES256_GCM,data:u/xyo3gpc8g3Yc9SP0BlYTqwzaVGxQCr0zqcT9YBg2FF20QfamtWZ5kBsmkC3O9ffd2WRweNDwchQcCCiaHzKYRVZx6TlkSOIPMbshEjD5at1H1xmAf4JOX6ioiCFQ9fHMc1VQGxFNPDNxfM6JqSEa8QPXUEleJtvO3HovOMMqA=,iv:7aNGFP+hCu2FzEzP6sQxXxe/RnUBHNnYgZWtApMhlVc=,tag:TO7v8YHW+OH/x2COkvXTug==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
