kind: ENC[AES256_GCM,data:iiAXoERz,iv:LEJjCUBdwVsN5Zg9C3b0q58BoIj5i1TsClRWP96guDU=,tag:LGrBXkMQXgwrFRNFt/PE3Q==,type:str]
ansible_user: ENC[AES256_GCM,data:gy/JYA==,iv:0teleBZO5UBtEW5FlzIqx10MVItzLz4EQyl+WDGjDwk=,tag:pJQXJDMW4oP89U5dwcqS7w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:0tLSXUph3mY=,iv:uGOXnFInO2I/uN8SXjlNvv+QP4uhJc54FI7c7hbGzXM=,tag:Nt86oJG7JEJol6l770No6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekglqwyv6f4pq359thxuzaxvlu932wzlfs223afputtnxlvv949spkxy6c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbEFYSnVaVk1yVkNERHYr
            MnNCai96S3VqTGlPYVJ0MEZDWFo2QUxTSVRRCktpRkFUVVNEM2dMTUZWYXpYQjAv
            Y1NVOHFGeGdKZ3BIL0YwZGtYRGlRT1UKLS0tIC9PT25rRXRWWktNVmtTdWNNdi8y
            QmxaNGZad1BnTVZZT3RMUjE4U1lsM28KvxJyvWYtISoCtNjjTuCkisTsnrOuSR2t
            i2fMNldenDuWJRCVViRLv/vxJh8D9QB3Gw+bYMRpFizNlFXSQ8hYdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-02T09:19:54Z"
    mac: ENC[AES256_GCM,data:GlilnoLNlAaNeQ08QkRV7XwNkXaO1rFKtBXZL88beT2rYWcBofMpxWM+d2ACixpnyz8GTSC/cA0ryzQx4KVBos0PEwaLtLe/4St7+d329nX/7QCDsIyOdOKy9iJjpFE0RJGoLDgGYZDKhbj5tHYWXJ0MsfBi9GMQAC9q7vMogVo=,iv:JYBNvH3DgZq1X+Xy6NDz8bLgLtrEptdYKZUkgkHRLsQ=,tag:c6R/K/x8klRQvlIh7GQCAA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
