kind: ENC[AES256_GCM,data:OebkNBhf,iv:33jNUX10rh+QGl/R6Lc+H57R/V5rKyJdRjLp08H3Djw=,tag:T2Mydm7Fcanqh0y3qO614A==,type:str]
ansible_user: ENC[AES256_GCM,data:N4B9aQ==,iv:qrSglO+46gQML7HrvWz2ps1FDpdvbniVSCEn1vPrZt8=,tag:FHDCVuhgtvALd171vbm8Pg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:aRnEkMLMpKY=,iv:JufeIBB9vrJxd1uzyF8Is+fg2a/M0UPFKIuQ6sILlxE=,tag:+VzeM/s0zpVviOSHO99NvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekglqwyv6f4pq359thxuzaxvlu932wzlfs223afputtnxlvv949spkxy6c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbEFXVnRqNHRPNU1pbm5u
            ZkZpbnhmTVQxL0lJS3RzMXhULzNuQ1htQ0d3Cm1XWk5pNVhnclBCZ0JJdGxnZXRN
            dXdTcmtTZGkvRXhDUW5nRENFM0tjd00KLS0tIHhSVWlEcXc4U2FFN0VuNkI1UGpY
            WnY5WE5IMW11aVV0L3kzQURhUDF1ZGMKJ4NK/y9qukWkFRYt0Na0Izh3wkt+FE0d
            rwcbO0OnKOD/NsKHo0MzXd3Pi4X8I4JAFNv0lz0oxPLiuXUNSiXl5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-25T15:23:16Z"
    mac: ENC[AES256_GCM,data:mmEN7O5B1Hv/0pvHXzS8wsR+oeThX5pxmh3LWhHuTWhhDPWNTUr1UJ3M+fsasyFQH83yPCU4ECwPTx4LL6CxCFoFHdSoXIWYusZeILMWkWytz6EFIuqOnSzYeKhLSG7m8QDNFZRnXtpcavVd3NcYl0o3UoeH1BrBbKHz4OxX9as=,iv:JAMtb0gCYrTWdK2cdapN/zP9THDDeZj9xdQvWxZXzJY=,tag:iD34PClhOkdk6P0eS/mwjg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
