kind: ENC[AES256_GCM,data:lRMhGx6y,iv:TD6jbYzMOv4PsQosgkpaX7mbFA/2qY2BO92BGvmPQpw=,tag:apa71OIrwb8sixUDXw0Pqw==,type:str]
ansible_user: ENC[AES256_GCM,data:Xn+S0w==,iv:xjptTPiIXKC3Nu7LJtehAKdeOu7gdL6spQQDzEET0l8=,tag:1ofp4SnB3HBl3B/soHHLyw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ihNpPqS+euA=,iv:AZHKNuorHtb28OjMSS7g6whtfcEdURv6RrC/qMVWmek=,tag:NrwX17vpm7yeUtXof69D6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekglqwyv6f4pq359thxuzaxvlu932wzlfs223afputtnxlvv949spkxy6c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYTlsbEx4QlNhcDZ6cEJs
            ZGV5UUFoQk1oWGhFbitsejBwMGdVSVV0amx3Cnk5MmQydFdKaktLeEJvOUlpc21p
            MjhPSnFLQVNBd0JhQzdhdG9yTERPZUUKLS0tIEZSdmd6d1ZnUExqc2FRbWREdG9M
            KzE3bW42MnlqSjc2Y3Vpdnpab1IzbVUKuAgaP/YQgVIbXLC3ltyxowid5IaizB9z
            5P8t1/iaDla+kWVcwz7q6v2P1XVkqKVwctZuUtxIQ/c2NrzINkyipQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-02T09:19:54Z"
    mac: ENC[AES256_GCM,data:VrnvIz4djYeVngbBd4JEoluprn3/g016qSGWxYhoaz6sA4LSDxNhIlQ26tNbKUw6hbf14DRWmpgafH0soiA37KpQ8GI5lBubWf4VBKrZvUq1hR+kEopC4VJchk/hr61BAh1xpIXdl2AgBG4ayNkPa+j9eUZF/3pgsTZn2TwXZOs=,iv:evqXfQ8Jcsa5aju82DDwM99KOXiNIF0OFEW8d2xMDTU=,tag:/Fu+1x8qhHysgKKufyjuWA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
