kind: ENC[AES256_GCM,data:SnGVJOfg,iv:iVNXQSQkPfl6tPpwpvIvxqNikY8uQDR+XxNgjGAlKhQ=,tag:beBsW2gAiZ1Ma5w5iSz6kg==,type:str]
ansible_user: ENC[AES256_GCM,data:7Hz1sA==,iv:AlZf+gMZtVfWVtLAgoodWsZxH5BQ+PLf8yC4WDdcFv4=,tag:YsQGO1AWF+vHXzH54X0mMQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:9p8Cx6Qro2s=,iv:0y6uunsy9WMwdIoCqIzUjlFVWD+2juxfhzr8wRAlrRc=,tag:+Llzg4nU+JqboetOWNQ/Vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekglqwyv6f4pq359thxuzaxvlu932wzlfs223afputtnxlvv949spkxy6c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdEdkdjB1NmhISUZjVlZk
            Yk8rU1c3SWdWZi9QZkpydFFtR0FQd0VtTlVBCkRjY0JsVGxHOTVrZTcyaG9INkF6
            bEdVZ3VJS3AyMUh5dXFOdUZQdEhRMXcKLS0tIDcySFVxZVZ2VXVCK25uOWdzaEZN
            Y2dTVitRdUE4SWpxQ0dLZ3FWY0VuUEEKO15yCMgNzBunEaxGY9XKf0eFHq0+d1vy
            ypBG2SxVV8shZ6Wzi5Oz+XPFhpuS4Ga1zMsIEG7YbgOghd/k0BL0QQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-02T09:19:54Z"
    mac: ENC[AES256_GCM,data:95CtaOvNrlWD8o4mrG2M2U5ds0tcVcE+uFwatPPBq5bmZIlD7CARK1ce0WzjEzlTRgYFpQZh3gnPJfYK6F29NFdR/9z4qyGyR6rLqvIe2t3tnwgKnD6ZipaAhzFpV5JMzyI0aOb05EpNliW2gU/iUttjRxBk5CuQWlMjIieEn3w=,iv:nFv923h7osIz061eYy8eekou3uuNd2UHia/rvUne28g=,tag:JjMo8W/iR826pumKSFaDzw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
