kind: ENC[AES256_GCM,data:NXrQjil6,iv:lT89Dz1BoP9k5XTDoR5cjiCYBZm4p+I5Dq1bMQsoWcc=,tag:tpuzR+eYpaXp6vhyzwbKbw==,type:str]
ansible_user: ENC[AES256_GCM,data:wzspHQ==,iv:fgtAu/bMS/58iQ9ZL2gDZMGcuPbOkGaH5Yd4YwIjbuo=,tag:w6i6GMmmb5mVXfv5aQP5fQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:uTI8mrzXYyY=,iv:WgN14/kG2Ozqfq8pDjXMdNwyGkv0i27WooKvlMyx8FY=,tag:rrTf+oKCYkETxRlPij2c9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekglqwyv6f4pq359thxuzaxvlu932wzlfs223afputtnxlvv949spkxy6c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWVIrVWtPYVF5bVNuTUh2
            aTkyTUdua3AxeXc5L0pnbVVGUi92M2ExZkVzCmhMY3V1WkdUN1R0NW1jZmJDbE1F
            aU9hYnc2R2p2cFJ5N2dPQnIvRy8xdDAKLS0tIFRtNTdMSzVyb2tvMzY1cmlnSGV5
            Yi9tYU9YazJyRGgzc1RVZkhZNlRJdmcKIcnKw3WKDqMy1E1sCrD2sRdL95dDHcIR
            WyEMPbsL0A0F+u1J2Icf+MCzh8cx8d6YsofCj0dt3b8oq6i5PMeC3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-02T09:19:54Z"
    mac: ENC[AES256_GCM,data:UcsGNcrPg20xJ5dm0uq3PuRZDOgbLcOVvn/Smz7Ns2ut7+Ee4UBixxT3RDgLo5M9t8uMD/PgkGBo0iq7dv4Yh/3Agc9gTODocqpWXw+u2ifp8she3W2+6DXPjfNGWOWqxi926HDFR6Tak8rIjH773nbT6qq+0k8To52FptMf+/w=,iv:guV4TKS0fTMNwMecBWdQk8JX9qzYSrDSkMgrGtyh+7g=,tag:KXi5DvqYPwJfc896mVvAAg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
