kind: ENC[AES256_GCM,data:I3df7fe9,iv:hx3P/QbMhzcQ337h8IbPhXeyFP7JT6pkeuzJDa1fv1o=,tag:jlc6nAyyM3aycVZ+UD96eA==,type:str]
ansible_user: ENC[AES256_GCM,data:tGiV2Q==,iv:Od/I0FBui9EG91Yf1CejtLPJc1C3iCxwv4cWLDlkDpI=,tag:3AqOyRCLXtAIWQieSsn84Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:DvC98U/H4Sc=,iv:L0P2CNpoA7hP7SRQ9HLeEmdHmbG6Zwk+r+Kq3PlaRDA=,tag:A7XYiBo2D/upFsDpO8iIMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekglqwyv6f4pq359thxuzaxvlu932wzlfs223afputtnxlvv949spkxy6c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUTQzSnpUVWtkQ2NNQ1RO
            UlZySG9VZFpzOUNNb1hkaEpHMjZhZnB4TzNJCktVRnFtZVJ1bDZCbW9PTEpQVGpY
            dmNZL09xZmJkY1hRdGVHV1VHY29idUkKLS0tIHplcWtLQ0NCa1ZoWWVRcm8wR1Z4
            WElJVlZ3Sk00Z2MwNytmSkFmK2piaVkKheiZRlpbsPuabi2qgpH4f1i8Fd39RKCv
            RVG0e/kAJr09gKOv4J0jH/k3FQqgw/fmFSNOpOCwXbxCZ7ZD6Nx24w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-02T09:19:54Z"
    mac: ENC[AES256_GCM,data:gNFPzybhNnw8iV35i0SNkAr98IjI/t9NRpFtCnX2uU50vtspKFN1dSKbBi5zl+s6MEhRSl+w7Er6UU0aKDJSR11RX/O5OV1UtiMn/WUbGvZFhKfj44H+phWLRFvbHFvsue/sYWqlt/YueN16DHmgz/JGyiZ/pBY/omAhgxRejJk=,iv:uR+3i6st9Fm+++24tOqrBbdM6JDZ5HiI0MTDIa8gCO0=,tag:X2h8NmLwocIaWD/Y2ViSQA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
