apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:EXGw19At+kmGaT/aFh5qNUVlxrFqOW9b79bDtYG4m95Ne2hD,iv:3Y5kJeh62KeWrNI5GYyl4EmKGzb0jj6b6TllzyuoP+c=,tag:ZLaGeFaxSj3SgSJKBS2aXA==,type:str]
    credentials.json: ENC[AES256_GCM,data:X/6eqEp+vET+F1b/5Hlm16uDB007iU0ilu2cdqxli52oSGpfrLd+2WqI3fDeZDFuOiLjWARiAuDR2SS1DmcgyaD4KG60a47U1Lid3S3KZCPJfGrkuN7qUNBx7HANZIhXCNEMa0Cj6PQRlDZGgvOlyl7OFE8osZGspJe8b02jkkXpwTQjMESAGki54W2IFC56918uu9N/Tf2BlE5zb6A2Hw4Gs3FX4qxdvlGvNZ/QRw==,iv:CX5Qvz9JhwclkPin7tjdg7f/pFq6F2B6W4nEqzhMxL8=,tag:taHnphs39Lz/lbBrV+Vbyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age155j7rnhzl4qgq274jwrlyg4j6rfv38rhg7r850nmz27yxr3g2ctsjmq72t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUEhnUzFhQzF1a2krR0E2
            RFVLeXBzenYrNmJqSHoxQmluS1o4M2RJNEd3CjdRMDVSS0ExaFNQUTc2QWJJbmFL
            NE9YdkRaaHJOWXZ1dVF1N3ZPSGtnblkKLS0tIFIyYjVocjVuWXl1SjAxYXZRR0Fh
            Njh1emtRV0N0czlYbEZFTCtMaFBUcXcKaZIFMVzs5OGaMVDB3SDQga60NRLNALzJ
            iS6xMQe5NdMCMDhHo5Ym+qSTL3cOmfQr53fwkCrzqblHq4U+uZ5KBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T05:09:30Z"
    mac: ENC[AES256_GCM,data:SFy14SpIVTUZNORN6PmY0wAiEqptPnSjTt/1wDpPbsc2r6qZB8bi7IpWhxYyYPaCLdO8Faol9INQc/C5/P/gVA3VFQi0yPHjwclXGjGLU9a439iXHZ36rL3xiG73fJoYZFxVQnoACirvLdUy6DJFz2GfOfAqdnSRxV8J6DJQmLE=,iv:ZR1+qejw6izz0iE3KtEMaKMizuUWTc28JUn9wxD4U0k=,tag:KgalzxquCh44y8nG3Mk0Hw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
