apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:+xUADCphtiOTb0gh1DcyOMWbLjv8Yg+SVan2437Ru3wYv+iv,iv:8zz1Ct6ySgbFDfIvTQbOdE5bfHteQHWi/xppgVUOh0E=,tag:wkKqiov69J/i9yN3IV3OqQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:X3JD5RKNkfepmCfDcCsBDLiaH+DgV8LZsT2E/c9Ga/PtZm5c3n/qKTEeky4xtzjxxYJ8oimlDLtx0SCJtQquPeIBTkFerXYhfJryU//awPp9ASzT45QfPH2CEvLTY2XUTHXFFamxekwXs17nMxRw3fQQ0l4ITrrZtEG13bItRFB3ErWdYXV2aPs10wEfY+NBgwcwS5SHXElhMeooOFimK1MJL+qNJq5nzZMGHxqXxg==,iv:XFR8EifSVkfNybAX9wXexlitBGLu6r91Z59fqZwHN5E=,tag:HiCoDF6swvgEHogr4THpLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age155j7rnhzl4qgq274jwrlyg4j6rfv38rhg7r850nmz27yxr3g2ctsjmq72t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bjBBKzlJbGNWMWhLYXNi
            YnFDaVVlNjRia04rSUNUR0lLZ3ZNak9ZRWhRClJKekRleHdrRGlYNVp4NnRlaDJW
            cXNoeEVNd3JpVGR3bk41V2ltREdaZ28KLS0tIC9raVNXbW1RbjduclVSNXZxWFdD
            Vmpwc01Yc1F5T2I1YWs4My9CaDUxNFkK/25OfmxI8qbvgyi8XRALapr6A0aaDB8+
            FmnGaPXwHnuKTBcdsKBo53FaNMJLJHRW7Ipfc4CIMiG6yYdb48kzlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-21T18:26:05Z"
    mac: ENC[AES256_GCM,data:kFARgTDjN02pUgg7M0nik/4mrtCadPn3+FugP6lk2RLSs6TWyGkpF5BvKrcXQFGerZmGr1AJvTZQIRJdMMSQIVn2BpkTxEOqpFT8XmMKJkDBcAUEDDaWYLUObY4OUBheyxlbBTYH6u4Wxj8S4tk6RBH58UhkewgQuMpli6sV6Ds=,iv:D9L5d4/T1KAOtjFc0gzB4KCxya/BNzQw3UDZ8GUSKVA=,tag:9Z7TApPHasltJEwENn3kRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
