apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:WP7OeYFoYM2slNq+SCTpv5KBGjp74kfLYGUX3G6hAwffYV+W,iv:fxwOOAE0AB7hJy0njxTfHHcaor0THI6VFuJ1Djv0owM=,tag:p5SyBWeYr/H6xYndcCc8nQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:FSwcXuYlbQ5ROrR1HsbB0siXXPI/hHap/8tlDOx7ee61KQFSTseARO98Pdr4T0C2kWLNxw1sLa2iMM+CeymSblg7GV+RwFiUj6JRlNZCRDXuh8IcDT+CAMRrRTbUU5nufKFe/aCcpNFbB5FZM3mgqrKPkJeA3hYe6yPxbQFo8e4HivlUEyxFukN7nXwaMJgAPaqCf9IIfdbzrJ5K1UaO6mAPeJZnrb/Z0VyP+B1QrQ==,iv:piPJqCTuQDGYfLGUVpqgFuJ/BVH1eGklR05VoYHAIYg=,tag:Wpktj6HoWz5zS2euOsh2rA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age155j7rnhzl4qgq274jwrlyg4j6rfv38rhg7r850nmz27yxr3g2ctsjmq72t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOVlHamFaaFc5WUtIVWNB
            WnU1Rlo4K2crNU1ITEY1c2xtL2hkVjJsVVRvCmhtQVA2VXZHMUw1NXpNM05GNUh3
            WkpLRWg5SWlkSFBlRklEL1c0ZXhEWEkKLS0tIGFPZWhkS1BrOEZrY2s3N25zcTFM
            L09EcnUxV0lGcWsxWW16L2tUb2VHUkEKlX4HzrmtfBB+1xqAE5GsttLU4kqiQLWE
            8embQkC8G4/WLob9loGQnErzLCDuyZp/MQmSY7c6+o9/nYV9JQ91JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T18:18:56Z"
    mac: ENC[AES256_GCM,data:IyZDRnhyxuNRyn+wmEYgfEcBUo+DudnnxAVkFgdeuGn433uJsxek8tOAv9612mZcXKimM8DJFYFFiUI/4jniwwWuLcDmi+CW4SOu6Sa2rsp6dD65iXIG8kLeHDmTVlHP9dhjkpjBAfyPrmbXrdqO87/g4D6IBdOABdPSLCDkNbQ=,iv:3XXf1bgtFxGCmoAQZqKPzGbavR2Uy1YuH542BoOW110=,tag:SYGHdUXZ/Re8nSNXrQoPJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
