apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Qc+IU8lp357u3BVReawiCoFQS+PvJxLERN7FW+I/yCLSN8kQaFILA1k8v64fp+cnx6XHXP0=,iv:2o4yMfEZUaVZKYxlT9zmyKN/K7vHArog+WpraBlxMM0=,tag:FfjEbtRxwXigMLmSz+WqSA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFL3FEeGZzR3F6VU9GYURR
        cm5pY3RseSs2b3Z0eXFrbW14bTM0OFQ2UzF3CjVJVXBkOXdPeHN5TWZNcEN1eTVn
        UWNLMlp6Q0szZU5jeTVXWlloUjlNdE0KLS0tIHVTcUVuNlZIdzZpcnFubVRvbklt
        ZlNZOVpadHhIQjZvZHkrNzIxczNqTGcKBVdWT/iDULXjJ1ZPxgDrtd0sKRaFfe2V
        lKxtbEUH/rwRaPYZG1JqYuhHCOoKLGLJswj+ELXabmSkYMvs21rg+g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1a8vdr200sct5atefmhhaqnxac7us6dd50hwg8e3e85mcmcd4sdgqnljfjp
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-21T05:45:24Z"
  mac: ENC[AES256_GCM,data:DJxSK6ywBY8I9mv5SLP7jRmbMTeWRniE4GvA6EnnuA+enBwEN5Zbk/JO/oERsY8xCbgV9Vvo6EJoUnbsmhJy8rcR8fMCn30NkSPWFugi7fFmHzvURGtZDK1DyEBCVSRAV56j3773NHjOSspDMcvEQpXmmTDJQOurY8FoFQffB2M=,iv:enf/cPz0uQbw/YJS5mmdEuR9+P+J+kZybMYgSmAOlzI=,tag:p3kBuq6WjM3W953P1Td/tg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
