apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:OMM3Iq9H0kM+Z6gZbo5wEBej4H6xI9TYARZcCZcaDkrUh8HoIzUPaQ==,iv:iz9+RNpmBrQVmtR7finUfvQDIsulH3zs4QDrMJTk/qI=,tag:SXqySJ1VAnnqwPlKX0JwiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekglqwyv6f4pq359thxuzaxvlu932wzlfs223afputtnxlvv949spkxy6c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOb0xITkl1eklIM05QL3o5
            MW9HSnJLM053Q0N1WEt6OEtPOEJsR0h4VkNNClE5VVFKTFBIQU9sdnBXZ0hnMkVw
            bHlwSTU1Z2pZM1hFQTJ6R1luNWk4REkKLS0tIFVIWU9kb1hjUndZZWQydUFlaHRp
            UHNvb1FOS0xaU1JzWHhRTmY3ajFEaDAKr+HoOhd3juJle6I4LPB0qEegLAwGaLCG
            GVXmnEmWbP+5CgkqcbfQHCoR/x3zz7RiTYzXMhCMlEu/mxeuG+8ecQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-02T09:19:54Z"
    mac: ENC[AES256_GCM,data:7omkNQmfpONCAdRnMNAduwcOvfe6EMQ/HhdAA7Mw59ytb1mXAVOGYLwGdNrcsEVWZoFoZI16VQPuJEZYZOtTJpWGyasNhim1MKh0uBxezjuCTRB63ZmT9mQxqJsrcHAxVbzdHFIZTAv2NJXrjOu4CLxe7US1qTuiVB7BLh6UiF4=,iv:RdaOcrnlXJ9t9aqv+vzgw/9sw+JbKh42M4xZIO9fHmU=,tag:HVprjMAz7/g6+9Ey4yX3Sg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
