apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:3bIXo/NV3LeyT/IZJOSVjhDcPPcuJhSxpwfvOTcTXK3k5HXzL//Grw==,iv:hKumoDaYOCHxo3fZbYY/Ef2zCp2iNkH5XyVZA/s1rGg=,tag:D7FtOu57LKWJaDA3xYz/1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekglqwyv6f4pq359thxuzaxvlu932wzlfs223afputtnxlvv949spkxy6c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTklCbURYa2M4bW9LYUc5
            b3J4TDdsQTR0emZ6bkRvV3pjOVhWdVhBSWxJCkQzYUpsalFuL2dLQlhsZU9TN0tn
            TzdKMjJYTkVFVzlwMGhMeTZBZlB3L3MKLS0tIDRzZVl1NEdsdGM0b3RwSUxhM1hh
            eTlKYmtwclVFclVlSlQ0bytZWGxtRnMKBXB4defEqNREpjVUZ6O61hlmyb0zJuZ0
            XzygSQB9hX2vK03+NFuOiyhVor/7PDvhdboQicI51ixpc/sESCrcdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-25T15:23:16Z"
    mac: ENC[AES256_GCM,data:MrLonIid1FCzIHUtGOKJjXpuEOBnVTWk7/wjL2JrDxcLEuhxSVB8VsRT/RL9vr3QeLFMJrb3MIUsea357+pYdaIkEJQNeyBvMydJpeBxYOoaszQwKuI3Py8wMrAdJqvvOOn4WTVuRMOPq3REFtBxNZ23kaJiCpEwHH7KYQxxmFw=,iv:TxNZ1emTtQeaoiZHglb0Q5Lk2d14mOn5P3G0EXkPpk8=,tag:o8AeLvBZkKLSYDPfpdxoHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
