---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  chartRef:
    kind: OCIRepository
    name: jellyfin
  interval: 1h
  values:
    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.11.11
              digest: sha256:45f648c382a0c8b552582fcea40e95cb17c5d475473a891cba0eb7523fb92112
            env:
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
              JELLYFIN_FFmpeg__probesize: "50000000"
              JELLYFIN_FFmpeg__analyzeduration: "50000000"
              TZ: Europe/Stockholm
              JELLYFIN_PublishedServerUrl: https://jellyfin.${SECRET_DOMAIN}
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8096
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 30
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 200m
                memory: 1Gi
              limits:
                memory: 6Gi
    defaultPodOptions:
      annotations:
        backup.velero.io/backup-volumes-excludes: data,tmp
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["jellyfin.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: jellyfin
        globalMounts:
          - path: /config
      data:
        type: nfs
        server: 192.168.20.20
        path: /mnt/Backup/data
        globalMounts:
          - path: /data
      cache:
        type: persistentVolumeClaim
        existingClaim: jellyfin
        globalMounts:
          - path: /cache
            subPath: cache
      transcode:
        type: emptyDir
        globalMounts:
          - path: /transcode
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
