apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:wN2erbnYLcZbFbTaZQ==,iv:6WggqINk/ep9zoI5X1WCr/pm/5JElaDcVxv8JyoKmPM=,tag:mIU+PZnbatFBNp+zJV/Gww==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeWUyY0ZjYml0R3hVUVBT
        ekZpdnpSTHRiMUxPcVJ5bENJOGJQL1N2SjFJCk96MDBMZExxUUFEd1Vrbnl2Zm9p
        UnlnSVcxdzFOOEs4OE0xdUpqcXlQd3MKLS0tIFljdHZmNWlkZytnV2ZmditoZ2Yx
        OWFFT1I0UlpkRFRqS24waTZoY1M2SkkKXA/t9IfS7PZDmlZXJdwumJVRoeVmn9Nn
        G88K0lz/yxiXovW9n0JCYIcjlrlXcVF+1Xe7sYPuKTd/W2mRvx7Tgw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1a8vdr200sct5atefmhhaqnxac7us6dd50hwg8e3e85mcmcd4sdgqnljfjp
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-21T05:45:24Z"
  mac: ENC[AES256_GCM,data:tCFglkXtgeEkoKCmsUxfyCR1JHXYigR+HTIkRSdRH57RLUZMxil5/9mXsTGMF0ZfBlM+I6piN64CbtiIoLGH83IoCgG9zxWl3yYPwZ/smjeHisxRZKwTTf/ZX8YKOOlbOM6IAXUOgRfaGuU7YvGTfoR4gH7Dxcv9iyhwIyt1zHY=,iv:w8S3/sdX7dUmEUwB9viBgI+f8tA1VvCdhUSFwo+0JKg=,tag:JT0RDwDv8MMR5oMQyjEuWA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
