apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:wN2erbnYLcZbFbTaZQ==,iv:6WggqINk/ep9zoI5X1WCr/pm/5JElaDcVxv8JyoKmPM=,tag:mIU+PZnbatFBNp+zJV/Gww==,type:str]
  ONEPASSWORD_VAULT: ENC[AES256_GCM,data:w8wYMfOg2Sgr,iv:o8GAHcbOqkId39PVQiAYatS4yu6GdPs7FRTkzP+ve9U=,tag:WQ2qOrCx1CfdloyEreso5Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeWUyY0ZjYml0R3hVUVBT
        ekZpdnpSTHRiMUxPcVJ5bENJOGJQL1N2SjFJCk96MDBMZExxUUFEd1Vrbnl2Zm9p
        UnlnSVcxdzFOOEs4OE0xdUpqcXlQd3MKLS0tIFljdHZmNWlkZytnV2ZmditoZ2Yx
        OWFFT1I0UlpkRFRqS24waTZoY1M2SkkKXA/t9IfS7PZDmlZXJdwumJVRoeVmn9Nn
        G88K0lz/yxiXovW9n0JCYIcjlrlXcVF+1Xe7sYPuKTd/W2mRvx7Tgw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1a8vdr200sct5atefmhhaqnxac7us6dd50hwg8e3e85mcmcd4sdgqnljfjp
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-02T19:16:59Z"
  mac: ENC[AES256_GCM,data:3/7iYgt7e4G3fUJL/iuwRBGPBKcV87gOQ+esXuglJ2FJWPcxv6BdZAF4jUyarHOBmQXsaBA/1x6FfF8TZvZxY819QeVutTzjJuSQF6fJ0f4r7tNzcrtRq5zqrcp1jz9BAZCqBU2T6tz0fnwBdWGy6bcPdHBqCCVvBTGUHBGQark=,iv:yvZ+mXg/joJMVN9gv6mcCoCw+DhApYMwIfKWNZo2dPM=,tag:7DnsvdOunuF1+EOYtFs+/g==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
