---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 192.168.80.51
    worker:
      hosts:
        k8s-1:
          ansible_host: 192.168.80.52
        k8s-2:
          ansible_host: 192.168.80.53
        k8s-3:
          ansible_host: 192.168.80.54
        k8s-4:
          ansible_host: 192.168.80.55
        k8s-5:
          ansible_host: 192.168.80.56
