---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: deduparr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: deduparr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DEDUPARR_RADARR_MOVIES_API_KEY: "{{ .radarr_movies_key }}"
        DEDUPARR_SONARR_SERIES_API_KEY: "{{ .sonarr_series_key }}"
        DEDUPARR_RADARR_4K_API_KEY: "{{ .radarr_4k_key }}"
        DEDUPARR_SONARR_4K_API_KEY: "{{ .sonarr_4k_key }}"
  data:
    - secretKey: radarr_movies_key
      remoteRef:
        key: radarr
        property: RADARR_API_KEY
    - secretKey: sonarr_series_key
      remoteRef:
        key: sonarr
        property: SONARR_API_KEY
    - secretKey: radarr_4k_key
      remoteRef:
        key: radarr4k
        property: RADARR_API_KEY
    - secretKey: sonarr_4k_key
      remoteRef:
        key: sonarr4k
        property: SONARR_API_KEY
