---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: deduparr
spec:
  jobLabel: deduparr
  namespaceSelector:
    matchNames:
      - media
  selector:
    matchLabels:
      app.kubernetes.io/name: deduparr
  podMetricsEndpoints:
    - path: /metrics
      port: http
      interval: 30s
