apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:6EajZCejdmKZ83fwEl/XGgl/oJv0dzI/JSdvhoFfMa8=,iv:CeF5d/rqGiWbOeW55PzKrZkiFCIrUfbtZvppqS0ESVc=,tag:5Zyz+OJksMtMq5Cjhs0rAA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIenp3TDNtZVpmY0UyanJa
        K1hUZTg0RWJPY3M0SFcrZWh5M2dBYzh4bTJZCndmMmtJYmhhN0FaNGJ1QnAxVHlx
        RXFwbDFqS1pjTE5yVDRLYnpkRHdDb1kKLS0tIEhYNWswWWxScW1lOThVZGpvcDBK
        Y3hScjI3YWVsZ1RmN3Q5NDZCMkpob00KJnaEVhyED/t5gUjLC7BkMs7zqFQwgZXr
        OCSLe44NystssopH8tX4bcvhhtnb4m7Ce0fwikYq5+KdhMLAaXwIVw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1a8vdr200sct5atefmhhaqnxac7us6dd50hwg8e3e85mcmcd4sdgqnljfjp
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-21T05:45:24Z"
  mac: ENC[AES256_GCM,data:agN2urdkEmj5TEHb9kjM62I95Viuo38KpIeynU6NScstVxpTEt7cV9mq1OYefktMoLKDkYkZxKi3dajHPGcnelNzzj/Vis188iy0u+FjdPSrYdJBDgCC/3+3FrKWJVph/y2YfrZZNLX29i3vECSrAzaHn0vOORucW1dGMhIlHZw=,iv:64FWBRwBKYwdP952LUqpcPsJWWyW2ZUKFjd63eIYZ74=,tag:DHtxRU0ZSb0NUOzQcnpIPQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
