---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      data:
        SECRET_KEY: "{{ .SECRET_KEY }}"
        POSTGRESQL_PASSWORD: "{{ .POSTGRESQL_PASSWORD }}"
        SMTP_FROM: "{{ .SMTP_FROM }}"
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: smtp-relay
