apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:Bn2prim3uSXd4plZ2R9KLY/0BvR2rd2HBz54F9QjSJWZww0IsA==,iv:eJ719ETRE3TSEFvjL6cLjEZ+xPEszjjWha0ReNmfobw=,tag:g4Opxe8hC9IYep59wl2kxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekglqwyv6f4pq359thxuzaxvlu932wzlfs223afputtnxlvv949spkxy6c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOWhjOUtTNUtVa2JhZHRk
            VE5HU1pZK0F5dGYvVHcxanVSMkgva1MyeG13CjMrc2pERklSQjYvWDJlQU5NZlJt
            Z3NtOU03UFZ6THh2VFVWVnV1c05JZU0KLS0tIGpQVXhhdHRLajhTNXZTc2ROTVRz
            WkxZc096R08xd0xINi9sVk1lZ0lDYjAKPJYYgPCQGltJky2xwbZ3ABHc2AbWcZTK
            +W8DWBIpNhxiF6zeD19ODlEy67HU/8qm3gOqvucA+6SiiBs0WM2SVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-25T15:23:16Z"
    mac: ENC[AES256_GCM,data:t2HJw02vG+zi8IrLHYWAZZth8bJObarIU+ArHG03yjifzQVet1E6sgeGVNK4e19WHiIJoYFh0qAjE9Foz4OlfotuAPn9XqYyABJKlKJ5X3mVy5Ho/CxSsiVMKU5flymRDcuimp4zfqca6BpGgbYpnhlZoXawrdzOieCFKkfaVnw=,iv:ip9hIg1tKAC7vyGMS7Lipje4f4PctZEDvKtbNbR+awE=,tag:G1Jhjsb5XZcm9oHgrJdgdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
