apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:VSzB6WvOI+mv6wMzK7dYMtifhiBLD1wJiedu6pnUb1Yw3mWqVMTXgA==,iv:L0jhUXaz3FJrhpsnXmBPDQeQafptCA4iSdkwViIU3Dk=,tag:IaQPilOOc/EfyiRhnJ0cFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age155j7rnhzl4qgq274jwrlyg4j6rfv38rhg7r850nmz27yxr3g2ctsjmq72t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3M2Z5UVRSS1p6eUJDM081
            dVlGL0IxSjAzTDZaSWZaRVJ0UjBPZXBjcWtVCldZd2hFdUlBa1hUL1ZiNUNSOGtl
            MHQ0aHpUNG84RGlESGNkRHk0c3pPTWcKLS0tIG5Kd3RNWlIyMTNnM1NsTWN0QXNm
            YTAvZmpkZUROUW93ajBxT0xxclBpQ2cKNImJ8vUcjCvPLO6lPYsMl0hlhEaYtcRi
            cQS5ndK8O2gVyLH01gTVXlN6eMorPybB3UNpdFhfrpS2Y9U3VJwjVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-25T13:15:16Z"
    mac: ENC[AES256_GCM,data:V42yeHzwF9/207Mm+HujmuU/lVdAGZ8Pg28Cz8Aw+NIbLser+utUpMixs//S4SMzqqWmvKocv36cnNSEEcJJW1e73ufLB7RyrXB6JHzPCpR/q8unpzSJQX4dxMI2LfReeaCyOXDjt6hrBudy0JU7JR/aWDl9ptEIi8TbWozMj28=,iv:sgXvBMLuVtvw0oU8caIEcZhAbSMw9aI3vRjmR6K/gLA=,tag:ZQaNfHPFkJMXvXGpAcE3IA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
