apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:RHrnm5BjrnbndpXsr026nGFLizdT/CWQuz5iO5vP24u5bS8V6s9Q1Q==,iv:kdN3IWJl3GqVQI7d8fwvK/gwi7CREKjQuTswFRJ2CMk=,tag:CSqPsQzrDOhIK8HrBAxxmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age155j7rnhzl4qgq274jwrlyg4j6rfv38rhg7r850nmz27yxr3g2ctsjmq72t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZHJpNUw3eThXZkV2THJN
            SmRhQWxVc1QxTW9qODg4ekZTTklla29hU1NvCjhoZUpzeGlsREZmR05KRnFzcjY2
            TmlTeTV3c3c3dHlaelNxWlUzMys3eVEKLS0tIGxVNmdWNUU4aHA0d3l2REFncmdK
            N2RqeXgyZE9uNTRKWXhqQ05LSjZNMlEKvWIYDniS7NY1xonVXgmgCse3guYfWG5H
            Vn1FnzMwsBCv+toGP9Sltv7UMUk3xG353j+Y/HXF8MWB2LrxN6UogQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T18:18:57Z"
    mac: ENC[AES256_GCM,data:zYu37bn2zCmn9UrSwoasJmWHC2U5nofevP64e/rgAOrMgWclsOCM07TDQB+bDB1loWczusWZ+nYfy6pE1cIIC1bLe/ysgto0mIslWutz6Vm73kjGBRgjDGIyrbjarBMqSeF/c8Sw4pih9/4Um/+ltGfiC6mz1RWaKWAjMhoKoBc=,iv:QTStG52RXlo+Xj77yqPB3rtTBPV4osPrTf3wOE4BwuQ=,tag:PNr2lLm9nrK6mS8ISQI3pw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
