apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:iEnF1KtJcIGz4SqZtp8=,iv:HGRQPEZvI3kaoCsGwmrLaDiKVh8HMAg999tiEfmxmJE=,tag:r3jF11Af9a5ud0WHUzZdRw==,type:str]
    api-key: ENC[AES256_GCM,data:2WCnX0T4IR0tt5aYVMBFXqB97XD+Rd6Y2zk3Uz4KhigDo8iI5A==,iv:Wrz55NgiMDSioJ/Pa8Vox4XTlFsdiJbItsiqF+HTleY=,tag:aq0hMsN80XcT+x0e5gRYDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekglqwyv6f4pq359thxuzaxvlu932wzlfs223afputtnxlvv949spkxy6c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZHIxQVR2aXFkcjVKU3M3
            R25IWDVjTDVlWXo3T0NoL3FvWWxuRG93SVhJCmRrWTJZTzJmZCtHNmIrUm1yR1dk
            VjNvYmhXTHhQQkI5dWFZMkpyWjljOGMKLS0tIHp0eTRnR0Y4bnVrazJDVjd1aFFz
            M0RHYWtGZUZNUVE1VVJOTWt2amprblkK7Z5/Dofd8YqPK2vjthYq7YOlLm/QfUwK
            RB68LUXeyD0No8uupUVlleMITjOiuq3KWIIOI9he0/sCJPlRfThwLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-02T09:19:54Z"
    mac: ENC[AES256_GCM,data:znvp6D3L2YtTA289QBRKCtC6QrUPUKcc/ZRb1Zai5PEqtRwwnN7XFECPhUlRIYl7Upoe9nE5LS6GEInfnZvw1gj+Z37q4kjDoTZhmInp3BELgozQ2NtdIQZHvpevxVamU1iVg1BlX17ZegYIxKKJQ0heXgKzzP7b6hyc9vn7w/4=,iv:GppxOlpTWh6R/1ZIxbQDIrlhuZBpJEGouxOXLRdpx+U=,tag:lr+Do4wYCBCan+r9LOhDdQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
