apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:O8sBc1OB3NTb+5ln5W0=,iv:mTZoR5o5ghrEg6hzfNNSAF+ZQpGEWenE8pFDa22g1Ek=,tag:IaVYU2ZYZ5pycHWoXEtLxw==,type:str]
    api-key: ENC[AES256_GCM,data:/PJZTNMZRY+ZL5DHktKmJy1UzkRUD2NQbJf6udhchIOyJsTdfA==,iv:ex9yGdx7O2ya5DelAw9A6b4riz0QQAu+6fI3D03tjXA=,tag:QpfrIZ/BpneeSuvm21FZaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekglqwyv6f4pq359thxuzaxvlu932wzlfs223afputtnxlvv949spkxy6c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTHNYWVNZSFdyMmp1UWNK
            MFRmY1ZHU3ZIYjcxbFAxeDZMbWdMdkpjS2lRCmN1eHNBa3pRQkRqckMvS2NFc0R0
            OEpDYVdURFUycWhOYU5janZmdm5IQm8KLS0tIHJUNS9TUlRjNWFES0krNitvY1Na
            d1pobW5IUmRHd2VFQzAyQWhLZjVEMUkKIrpurJEXkP8SLX7KIZmX9vFuJAvxsbnF
            nz/sODCEIrSKx6+9NMCppe2OuHsfKOhP6f+uPx7ABwonLZ1XXfix5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-25T15:23:16Z"
    mac: ENC[AES256_GCM,data:6M9sOe6nc69bzA8r9hPCi7fNZThYzj737Xo5pthNX9ujTUoYc2My8D+QECrwCwt5CSKuUlNuf1lVDUWh4EbEyE21xlUfPaQSvcvSqqcQ2AB3FDXD9PeOQFWbIdDMlG9vauxC5YcJWOTpUao/YepkTZmwnO536WgVh4e49SR+fBA=,iv:gORHsZSJ8Axo0iRwyr/HrH0JVReQ9Z413i7MhoOnSWo=,tag:5I0ixSV8xGJBAA1qiAY1Fw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
