apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:feiVPe3NPMgY7n3DM6unj+QTuSus4qKn9E2FU4nCqbXsTHwRcioVdnFcsmC4xIqoQXPNQbaMp2cubcBsrx+H3q9QzoYnvFDwWtk47WE0RqXvXP1vTqQLNMSygEOZOXkYMhT9MGafOOh6xqDyDQs+AgHDjXmH8fT7qvDgQ0g/Y/tWowySNMz0C5+MaVmGEgCtpb/HMsucS+kRSgreIM6RkTa1vzfwx5SBgugajPrCo++5azoV,iv:4syxYWZ9RL8z1dxC+knoSTLVYD55XThLjvJeOMpT1kE=,tag:P1ysHWrcEqtTMQQieeclaQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQWpBTzhTaitPSm5mZ0NI
        QlVRMzJvanNDV3JITUVFa01CWjFaVGhxRmlBCnRLL1AvandXSytCTHIvd2wrbjYx
        SllSci9XZ3NPaEdHczNLUHFFOFNCTU0KLS0tIGxVeXowL1ZJdkNKQjVmaWFSVFVj
        Szd2S3NVck9CY0VER2h2ZDBGYnZtVmcKo7cClDLGw7RFAjBtPtdoL+/F5yFRRt12
        vg2Y7SG7ebx+lZblHO3UILEpMPGlnsyr9yPJ83y2iy/eBvi+ezyfjA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1a8vdr200sct5atefmhhaqnxac7us6dd50hwg8e3e85mcmcd4sdgqnljfjp
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-21T05:45:24Z"
  mac: ENC[AES256_GCM,data:TD9+t5WwwkFPcJF7JhUU5UoLqUOkueZsE1US9D25IzkIFPRDf4a96awq0HK7qmBefqvMEiNxrlfyM2AaTIqiKjp8vNahNH0S/Z+iIPXcngK1Z61dYdKAFEYmzSpTQl8ZZGAsrz5bWQ/H8ykn/1StuoY+zy3gnDVmPatwbU/Qdqc=,iv:s6OP4g+6Du0HOhN8bm9y0B2e87rmCna0zsAFlxjTel8=,tag:klgjdwhw7lnwRZMp3mPmjg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
