---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stirling-admin
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: stirling-admin
    creationPolicy: Owner
    template:
      data:
        admin-user: "{{ .STIRLING_PDF_SECRET_USERNAME }}"
        admin-password: "{{ .STIRLING_PDF_SECRET_PASSWORD }}"
  dataFrom:
    - extract:
        key: stirling-pdf
