---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stirling
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: stirling-secret
    creationPolicy: Owner
    template:
      data:
        admin-user: "{{ .SECRET_STIRLING_PDF_USERNAME }}"
        admin-password: "{{ .SECRET_STIRLING_PDF_PASSWORD }}"
  dataFrom:
    - extract:
        key: stirling
