---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
spec:
  chartRef:
    kind: OCIRepository
    name: stirling-pdf
  interval: 1h
  values:
    controllers:
      stirling-pdf:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.stirlingpdf.com/stirlingtools/stirling-pdf
              tag: 2.14.2
            env:
              DISABLE_ADDITIONAL_FEATURES: "true"
              METRICS_ENABLED: "true"
              PGID: "1000"
              PUID: "1000"
              SECURITY_ENABLELOGIN: "false"
              SYSTEM_DEFAULTLOCALE: sv-SE
              SYSTEM_MAXFILESIZE: "100"
              TZ: Europe/Stockholm
              UI_APPNAME: Stirling PDF
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 8080
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 36
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/info/status
                    port: *port
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
            resources:
              requests:
                cpu: 100m
                memory: 1Gi
              limits:
                memory: 3Gi
    defaultPodOptions:
      securityContext:
        runAsUser: 0
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["stirling-pdf.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: stirling-pdf
        globalMounts:
          - path: /configs
      logs:
        type: emptyDir
        globalMounts:
          - path: /logs
      custom-files:
        type: emptyDir
        globalMounts:
          - path: /customFiles
      pipeline:
        type: emptyDir
        globalMounts:
          - path: /pipeline
      storage:
        type: emptyDir
        globalMounts:
          - path: /storage
      stirling-tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp/stirling-pdf
