apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:VxjONV1cXLAvJoVvrd7IbnkjC0lv7ZwcdIyXk2B/ms6a/WpKfOVkqAvUS7qYPDxSrLmRSGOmkAED0Fsx,iv:TBxKumCPuEophN3cP3jJrD+nJ5Fyu6xpB6GAhdiFYGk=,tag:Ah2nVpTO7hcMeIfWYGHfzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekglqwyv6f4pq359thxuzaxvlu932wzlfs223afputtnxlvv949spkxy6c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTWxHSFJ1Nmk0SlZlRHBw
            eGc2ZEhhRDF0a28wb1R0WncycGUxWUxCYzNBCjZyRnV4VEVoWHFJSVpNQjNxak9M
            N3FoUWVzNmF3WWVjVVpzRVk5M2xBaWMKLS0tIGlFMXNtdUJuc0RrM1NxSTdJNWFS
            bkdFalpFL0NKZkthN1dZZUJ0c3ZkbmMK54pazkOwPSLfeDSa55A8Kz4dem0WGLh+
            xwPxvz0cYOnA9hLU9wR/VU5hsQZIH/yhvCb1OwHQNSae3ZNGlpC/ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-25T15:23:17Z"
    mac: ENC[AES256_GCM,data:bXZmtHn7F5WE+9G1pdKeUcC9n9hyrJ+m1AquN2DeVbQojfWSjAF/PzobbyGhuvM1d6ySwz4Nm1h4wJHZB1K0UnDRBWXIrGkPBw5ytPFN4kJ10uiaC0fv3qlbepVgCUdmc8HKM/gX7gHztoCWXYeGgRvVjLd6WhTWoYO8qsmOjeA=,iv:8JeOmPAaN4enWQuvWnE0h29w2+398tKI0wWpm/mXFcM=,tag:KZz+Yu9FIYgpfd7a9grKkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
