apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:kAV6v05H5/4Kegx+pBWKV/ppcRo8h2yl41E5FoPLQc0BznCwrP8oJmFx/XEnEvuu051T/c0QYZIwXAsI,iv:f2cFofwpAhtfU8EHFAbBwvQaLAo7jNJMm6PxHhmCghc=,tag:5IK7JUCPfwgidFQZ4AczkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekglqwyv6f4pq359thxuzaxvlu932wzlfs223afputtnxlvv949spkxy6c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMElXUFQ5VW1HbENyWEI1
            ajVZa2NXVjZaYllENU9Kb3VWUUZzR3R3NEZnCmxMQ1F5UVRKS0haUkQ0ek9ieW13
            b3dqdllacXpxcmhtZmV5djQxN01kQXMKLS0tIG9TejRGcDNTTEF3OXBxRmIyWHJk
            T2RrbnlGcVVBbUQ0MFVlNjVycjdrUk0KoQ1YpO1P2ONUb4kwLB7aWYBJy7fk+aOo
            lYQSsj1+6lzfZpyFIELcYpmqKM+QA+DzReuMvHYUTJiop5D5tgDLOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-02T09:19:54Z"
    mac: ENC[AES256_GCM,data:zHo0erSM+2fBdDvvLmyMQHqVqpSuVvGDWzDAwHrNl3PwlyqyDcjcqdMouTqMn3KkhJd+Ljd+cf0DkBuMudrz+MZloJ59Zbh4ZCIq0IiH3Zmi6Gt3xQF172+KreIqS0CrypIs9sH3OqK9erf22sL+5qX1Ywh1kdpWn7Ogo8K8VxE=,iv:2HbCnTCopTHQw/oBlEHmjQJCWDNttOATyUI2utes2JY=,tag:9t6lGjQC7AIdMLjRq+ATHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
