apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:DUZbllJM9PgtM+hZlIAFNCe3ga298vFmQr7VrSFvjmyrVgkjInUbmlkx25L2OIjztgyALvv/NSdRtXcW+9Pbqj+UI/hG/L9o5j8=,iv:3mzcS9MZ8rTLDduGHi4A1pLG7kYPxZujQ+RjErYE6vU=,tag:ZEgsCMHMYhgzm3Y8bWitxw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10t30tc0pp7zqm950zmuk2pzhl2tlx4sy0r4y39p4nr38vm80jf8q52urda
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eE0xZVlmTXZBUGtYWDI4
        RERkWkNkQ3RBa2FJWDFhM2trbjR6dmlpVUZRCnAyR1NNRkdQbG5jcFh2N2F0RGxV
        TVNKTUNjallRZG1jc0tVUXJ6SnFGb3cKLS0tIGZNeGlQNmdkV0FTL1N3aFJhakZW
        RHQrM0tzM2pCSXNFdG41NjcvUTNHdDgKI2hvMf4QaJ8QRexQ2zqlD0LWuFb2yy4y
        lytOgUBcwYatlzdaR1s+hnbF6WugML+iM7cuuLlNNpKAl0qVIxJs+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T08:19:29Z"
  mac: ENC[AES256_GCM,data:gAuCJz+5pfTsLVnuby2/B397RIGRuyAW+gOtkbrWJNErhsD0GhbD1Z/0+j3StbOh7jRT3jNTU8fjWOHshKwO2bWlaLhsg3JJ+SxlJzpbgORKQxjzU/jVXlyraoBI7Q4xM8+5a+ciZgTO9NWsEpdYYi80jhDjKySx7rgnwLorKkc=,iv:mwliebfFWADTTPFclp19iFKrugPBHkuCMRxyoM4G1Wg=,tag:9o6pgBtCrMLxZh5bGJV9Lw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
