apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:2kE1Fbmj4bg8zUByaooZHzjDTRej4r7PJG4MmlWgvZ9Yp78Bx8DofnGYBGFTXlWIA/fhD90=,iv:SeZ8zx/Y+c0Fdp1Qbii+rnSVIf647YLnktFo/Xhvd5M=,tag:uoobhA7miJXQ2cAYFUB5MA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVWxxRHBNc0lmRGhsVUJw
        UmpVcTJtTU1zL3VqTXV0WGhwdTZidVVObzM4Ci9TVTZVd05CSHRuUW56VFRhT1c2
        U09XZmh5QVY4SnBHalBtNWZCVkI5QlkKLS0tIEdPblhTczExOFR0SzV5MnVzWmdT
        UDZjR1g5eWhqS1NlSnZ6SW9zRldxSjQKnwXMtlTX1/lq9SdCKhKJ2PD40ygebndS
        KmJgvNJw6o9X1Ins3v9DJ8MKrcYzvlezSqtEZ36+HbGo8QuQoUhEzg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1a8vdr200sct5atefmhhaqnxac7us6dd50hwg8e3e85mcmcd4sdgqnljfjp
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-21T05:45:24Z"
  mac: ENC[AES256_GCM,data:w6X36cx1uS5nXv3LC1bk5GaJ8Ier0Wcs7IQkp+1SfkL61Yh4u0xfnLKgLC1FKLXKybLOfdFVB/C7GT54k+/50g19rq1kXW82lLLuf/5AK1HQHcG3vBiFow5Hgupg6N4Og4c2oVmdYwEDmlX1fokp96cLGT8uwGsZDIpa+JDiR+s=,iv:vfBdyLoDHcgtmUn9l7jGyNRIT5V/uyzAzZZHh2o2Qn0=,tag:8C9G1HtxxkbMeJ4NigvTpA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
