---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.20.150:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.20.150"
  - "lab.engstrom.live"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "srv-talos01"
    ipAddress: "192.168.20.151"
    installDisk: "/dev/sdb"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:ab:94:86"
        dhcp: false
        addresses:
          - "192.168.20.151/24"
        routes:
          - gateway: "192.168.20.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.20.150"
  - hostname: "srv-talos02"
    ipAddress: "192.168.20.152"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:85:85:38"
        dhcp: false
        addresses:
          - "192.168.20.152/24"
        routes:
          - gateway: "192.168.20.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.20.150"
  - hostname: "srv-talos03"
    ipAddress: "192.168.20.153"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:ac:12:32"
        dhcp: false
        addresses:
          - "192.168.20.153/24"
        routes:
          - gateway: "192.168.20.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.20.150"
  - hostname: "srv-talos04"
    ipAddress: "192.168.20.154"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:9b:9c:fe"
        dhcp: false
        addresses:
          - "192.168.20.154/24"
        routes:
          - gateway: "192.168.20.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.20.150"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

