---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: xibo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: xibo-secret
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: xibo/MYSQL_PASSWORD
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: xibo/MYSQL_ROOT_PASSWORD
    - secretKey: CMS_SMTP_FROM
      remoteRef:
        key: smtp-relay/SMTP_FROM
