---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xibo-xmr
spec:
  chartRef:
    kind: OCIRepository
    name: xibo
  interval: 1h
  values:
    controllers:
      xibo-xmr:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/xibosignage/xibo-xmr
              tag: "1.3"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 9505
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
    service:
      app:
        controller: xibo-xmr
        forceRename: xibo-xmr
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.20.145
        externalTrafficPolicy: Local
        ports:
          xmr:
            port: *port
