apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:yVov24RMaacwgg==,iv:ZRY9uHTYnXyE9fCRzhh14zgCUMssCi3V694KynKZtAI=,tag:OkW34uVyuLn7oXUlRFviRg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:yD2f7pTzE1FLOnMi+gw=,iv:w2lx8g1ULGCpjw7r+lkKsCyMsfV/Q59C9Y7vchowBYc=,tag:dSTcuNYysWxnGNg8R41MGw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:zIo5azli2iFBKWbo3SZU4demJaHVl7z8tYbhaqYXK8VQ1tW5,iv:Hne2kZ2VXeC8xktJBVbcOy/4CH2rxkJsxawRY3wFGqE=,tag:xoSCuTvXR3cQVzRF/aWRZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age155j7rnhzl4qgq274jwrlyg4j6rfv38rhg7r850nmz27yxr3g2ctsjmq72t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZk51bU9iNkxkby81NEVP
            amh0aXNSMnR5aVpVdVdOdW1TZUJCdkVYUUdnCjJhS2h2bEhhZUdTVlNMRTh0MDZh
            dlFqNFpaZU42QUFrMGJhTjhiUUVGa0EKLS0tIHdsaXp4ME9wc0ovWm42MGZGQXAv
            Zmx5YlBZaWlCc0EvMXpzK3RVY2JzRjAK/sDZf7fpJahaPavSGcZ0DS/aDP2tXpnR
            girq/KCSdFgkqaiFnS04EysOqPM7BmQ7qHcqWJ1xdU+uyaYqL0pmTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T18:18:55Z"
    mac: ENC[AES256_GCM,data:MdDFQRFuGO63rIXRJttnUZRmC4zuTPvflPHdPfXEYgQMuy/1rZBkOO2g0/dbsclKuM8dct64jpZziJE/IdPUlpDkYGLpVa6YwePXIAzssuzDP+8d69RJarVLEWAgEq2h/Nw07XGxGblhgKTIpaeo5H83mA9ZBWBc6cjSS26D4Bs=,iv:y7GR2c3FTUr3806IEddxDOopsPDhIJ/xRBx1a8Q6E+s=,tag:ktbTUtEJUzetM73xJ1b8jQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
