apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:y8knTPnovoh3bg==,iv:5CC7XQKFb1I2qrjt0qBkOn4L03Muqh9xdydAiczFqBs=,tag:WtbQDMktsmitMV+Cjq0j7w==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:9zpy3Zww3FwBEOG63fI=,iv:gUT+AgUXw5NH36pSXOccpAd7JJnX4WHxxXZV3sOSSXg=,tag:Pf1WGtEKCr0TdoUJJvrprA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:dKpMvV4+DUMe92eIYmtuaQv0EttCL1029aNVeIEMk6FJuwGh,iv:QoNfbpkmxSqTxD22TPUby60Bk4GiuVzbcuYXJXH/VyM=,tag:EC7N6dFSzO0enTmFUoVFiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age155j7rnhzl4qgq274jwrlyg4j6rfv38rhg7r850nmz27yxr3g2ctsjmq72t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUTdjQlM1eDFlWWpVMDhT
            SnhYelBqeVFTVWlKeXVSZFB4NWFKMkxsMVdzCi9odi9ScnNGVXF5US9vdTlSdDA4
            elNCZWxlbnpiOUFycTJ4NmNhQ0R0dU0KLS0tIFhqZ0ZDL0pWRzZUcUVoWkxqZmdY
            SG5EaERCUEhYMmtWN1NVUkRsMnllUVUKlnjynC68yN4UrX6SPFBgvSRmtyG/4pPv
            xnUiDphT5LnZcPbovDCWBLSsanbOY+4MNW4/dLu26rs9zZxXv7wcgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T05:09:29Z"
    mac: ENC[AES256_GCM,data:3TY5731ErcIfoDchFXf7E5ioQ34o5Ah5oRlCl/QBmr8V/DXlDWC2igibYRNmpcqp8OtmGCxOFLMXWmOJeK0WWnprx9EMgjIWMiHfhr6ZesLsIpSUJ9fb8LfebDwcQWVleTlFZxmaK7EG6jlHE5j9smYjsgQbukOmjSg6NHYxspg=,iv:3kc71GetCagfdqbYwpYUpa76CbSqorb6T0t1GSaRL04=,tag:x1l3NbYgfV12vADt4IcR8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
