apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:LlWKKsKR62bIoUqP8A==,iv:3kK3hUnlJcHgW+I+zd2kDpzOqO3ED76TDKwlqKLQXmA=,tag:A5f4TEWPYaZowEWr4iI48g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:O6DtpCFsFJ+akerq6Ak=,iv:XuS/FW1qWcJLRnQgGjS0cxiOKKpQRW+CQVYnP3LQOUg=,tag:b3Fn7KH+A+yDVX4Lla26AQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:u8Ms5a//YrD+e4m3WPHffzqs0RBsbIaQoLTmmm80fI78+yzJ,iv:UbFAiwKwRC/cfuT5I/rt/i3omhkhE5NYPWs3aSKDUj0=,tag:c88x2RqDK9TYZJmEoMgwkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekglqwyv6f4pq359thxuzaxvlu932wzlfs223afputtnxlvv949spkxy6c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQjU0MFNid0prNStGcG9a
            TURwMjR1MEYzK1Zod1dWc2FhVkVWWk10dWdvCmQ4b0wvU1NhUndhUnk0aUEwSW9u
            NU5HbDBjQUEzT0xaUlkxeGtWZFRtYVEKLS0tIFBwLzhnUW5uTytzTGZnR1E1MmJN
            MWlkQjJKd0UzTENoM29YbWFVTUNjNDgKy4sZCrXCNoSWtjK+pMhZL/CVN8WBQqV1
            4hwL3NGt7hI8UDTZ1C4/d/3OW8umaBmtSHQaIssnKc4c4YiVje9NRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-02T09:19:54Z"
    mac: ENC[AES256_GCM,data:awcH6l/NhQVEJY2XRp7rZm9ahcsP0tOIU+O36+BfAbjlEGCF/z7s4lbDh2XfPhF8JyTch5OLtB/maGKoYiqqq1gLCOHC5NVnz+yCEshQBSjaoBZcA89GCgSYmY1jtOtwpRXqMEumeAlMJ4XR4LEnwY2n07arOPzbw4DjJ1hSu3g=,iv:T4oPEbwjFzbib2EeWV2hAYigP0r7Q0UB75L6iBuL6yU=,tag:hgFth+/boOwLRDVzGXQAqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
