---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: nextcloud-secret
    creationPolicy: Owner
    template:
      data:
        nextcloud-username: admin
        nextcloud-password: "{{ .NEXTCLOUD_ADMIN_PASSWORD }}"
        postgres-password: "{{ .POSTGRES_PASSWORD }}"
        password: "{{ .POSTGRES_PASSWORD }}"
        OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        SMTP_FROM: "{{ .SMTP_FROM }}"
  data:
    - secretKey: SMTP_FROM
      remoteRef:
        key: smtp-relay
        property: SMTP_FROM
  dataFrom:
    - extract:
        key: nextcloud
