---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: family-nextcloud-data-nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    server: 192.168.20.20
    path: /mnt/NFS/family/nextcloud
