---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homarr-secret
    creationPolicy: Owner
    template:
      data:
        db-encryption-key: "{{ .DB_ENCRYPTION_KEY }}"
        oidc-client-id: "{{ .OIDC_CLIENT_ID }}"
        oidc-client-secret: "{{ .OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: homarr
