---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autoscan
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: autoscan-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yaml: |
          authentication:
            username: "{{ .WEBHOOK_USERNAME }}"
            password: "{{ .WEBHOOK_PASSWORD }}"
          port: 3030
          triggers:
            sonarr:
              - name: sonarr
                priority: 2
              - name: sonarr4k
                priority: 5
            radarr:
              - name: radarr
                priority: 2
              - name: radarr4k
                priority: 5
          targets:
            jellyfin:
              - url: http://jellyfin.media.svc.cluster.local:8096
                token: "{{ .JELLYFIN_API_KEY }}"
  dataFrom:
    - extract:
        key: autoscan
