---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: autoscan
spec:
  chartRef:
    kind: OCIRepository
    name: autoscan
  interval: 1h
  values:
    controllers:
      autoscan:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          config-init:
            image:
              repository: docker.io/library/busybox
              tag: "1.38"
            command:
              - sh
              - -c
              - cp /secrets/config.yml /config/config.yml
        containers:
          app:
            image:
              repository: docker.io/cloudb0x/autoscan
              tag: 1.4.0
            command:
              - /app/autoscan/autoscan
            env:
              TZ: Europe/Stockholm
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 3030
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 30
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: *port
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      config:
        existingClaim: autoscan
        globalMounts:
          - path: /config
      config-secret:
        type: secret
        name: autoscan-config
        advancedMounts:
          autoscan:
            config-init:
              - path: /secrets
                readOnly: true
      data:
        type: nfs
        server: 192.168.20.20
        path: /mnt/Backup/data
        globalMounts:
          - path: /data
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
