apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:6gGrx4Xt3BIOefE1RUXYPK47ah+9YEF6WR9ghailO5eIRFAE,iv:AbsCourZRT5d+i/NylbHIdHcuUgVgY0nSbl5Zf7r1Gg=,tag:5xlUi2NU58u7szB6As5V3g==,type:str]
    credentials.json: ENC[AES256_GCM,data:kPZ/mjRlH93pvUHC1sqhx9YXlCOshLh5f9XHTYwIvbMp1kpz4Cfs6nkVUss3O+gthYSEZmhzWn/xrSUhHrayWLjQLDN3lDFb9ffN7OI/HDjUM+YPGW2YQyosjoN8FEwWZzdFqWmKgNEK36ViosWP0M2aZxC4WbaiAQ9bjoUUz6svKURGOgcQfWZwksem8q3EnE+YT3t2QnJTTzmKeBucN+pXkzZrjo1Y1ydUvH/RXg==,iv:QnOa/a7nVl+qTHyjATltQCFE0EjTQas01A2oTlugveY=,tag:KFoEn0ADCfRY/QmtuWYtVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekglqwyv6f4pq359thxuzaxvlu932wzlfs223afputtnxlvv949spkxy6c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cWFuY0x6SCttNk1sLzdn
            RFJVRHdWSGV2dXIvSThZNmZXT1lBS0d2bTFrCmw0Q2I4ellvSERPYnFuUHhJd0xR
            YW9vMkk3VEQ1MVBNK3dteEN3cnI2N2MKLS0tIEZ6UGdBelFXamxwei9yMjNpQTdJ
            VXFSeXIzVE1KM25VODBEWnlQQUtaRGMKy8k2Cb/9mVuPWtxs6N1SX4RuBy3LNQNt
            DuR2vL34bHJZQPjIZbkOS+B5/Rmx3Jn3EEvnAyMF7FaFq+7z1i3z5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-25T15:23:16Z"
    mac: ENC[AES256_GCM,data:5d/941lT3y8dhtoQ8fMjzAJhyOy54IxsDf+2mYfblj9kpUGiMgXC/hImAq41Ojs4n+y/AuL6WmRD62HtvaVki4LpENsY12gbtXkMHePz+vOJhJdZOhBhlT2sxGpgJn9cDj19xSv4X5AoVhfxu3t+kirTIRYGJaOY99nfBtxHD/w=,iv:FGyJMlQr1962XbRuXqXB8VLuisv/g9twq6z2OjsWUhc=,tag:Rj3NKyDxF2qjvliS3bg6AA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
