apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:+ssLuJPiwUErB8ORrhtAl5WeQIljYNI08almj4tV8noOhP3W,iv:X2dDVWEKjf8Ip0mBuXmRusFAJEFjo2Tiq58NHXDiKbI=,tag:3TYsx0EYkzmiX/whjm2VDA==,type:str]
    credentials.json: ENC[AES256_GCM,data:pyOEYPVhio2M9FUBJ9/GxG1Zx5uIvc6rvpNh0dcVMSScisz3qT8hzCkNLAkq/J2JBobnxAd3A7LIBgb5LIawEn0MnTlHzIrtH4/I/OmCXZHLyM+sdpQ/dbtaQPt/0aY12KTX41gzh8f2QG8kDZ094boZ6FcmEHiMbgtus1JHjQOuaYSb/bNkj3bStezwJMZjt7KCqX1I6SnjqdmWGY+OyXKmQyIP21TbGs+wFYR8kA==,iv:ppeeMiXyIZxyis0mGC/dZr1JPnFVHn65eyPrmFPuhzY=,tag:51inBiIgBHfZR48ySQoCgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekglqwyv6f4pq359thxuzaxvlu932wzlfs223afputtnxlvv949spkxy6c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzakxWMUtZQUt3THVkeUFn
            Z1E0TTMraVpXZDhyck1BZ2NYcG45K3BQK2l3CkQ3bmJrNWRIYTFEYVZsakJ1WUNF
            NGc5NVg4SVJISDkwRjZ6ckord0QwdVUKLS0tIEV3WlZHVnhUTm10K0xKcU83SFlR
            dVN0S3ROUlJIT0dHMHE0Q3JaeHplWlUKA38E8BNNpS4vraHw+8wZCXMr6Q55vdHO
            dGzUddtHt3e/h3SQvjEYa2DdZ5PewDagDe1az5jRmCBGqOhrxcXTcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-02T09:19:54Z"
    mac: ENC[AES256_GCM,data:KdtBWlDehTtydOcbXDdorI1OAuIz+e+OAUIM/fMH+dCzJQaHkQ82WXsBh4Hgn8CxZ/VoLeSqA6Q1ZrNuPNwfbwIW1e/rCuED0pLRFDny+iewi3HkW5A+AAZK0W29EfdGgibdYvqIIrp8MEG7e4G0WbtRfY9aMGekdsqS5debDrE=,iv:jtAfE3YNCEIKxdMyk+O6J6/8cFabdQ7rjRoD6Q1OtW4=,tag:1/NVEo6RKkArHZjJtI7mvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
