apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:7qN1EVc9jHTdrmdIyfThJ35qq/6TiM/KrjeOGENL4t8=,iv:2T+CScMHGQuq9dm/67QMbdfAnoBeSyYPc/uZGYstu/M=,tag:JJHx3CK9DNa5EUI+j4dHEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age155j7rnhzl4qgq274jwrlyg4j6rfv38rhg7r850nmz27yxr3g2ctsjmq72t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTkxxOUpVM3N1ZDBTWHdi
            YXkwLzhxYy9TbjhrdWV6WVhJbUNkZkR0SlJBCk5PalZ5UStvcytHK2tURW9waFJH
            VHJ6K0JoSnZsY3hKOXk4d1JZSGEvVFEKLS0tIDZycHRPOXRIQ0pHR1NBeHN2MmRU
            UzFZeXRaT3Jnc2Q1b1VVVitvT0RsUDQKsaZYLODur5eDtRfaCioXa1YlIOhbrOmN
            UD7pex45NwH5Z9mCQO13y/aUIqepQlABofD+h1hOWUyXg1TApNkUIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-25T13:15:16Z"
    mac: ENC[AES256_GCM,data:8sHgMwsLlotk85JpiRO0WfUMjn26J+UNW2t070cn5scuu3MqlUqsYqGnGHQqlw+9+UnuIjIeFpntmVOFv8X966YQ7k3Wd4LhVe/jK9ORfhKg/oReyhYHwzbj1xJoNro7LpnOMhxQeR5SezXiteqgegVFgE3BQTYgapDFf/Neu+g=,iv:3SUATXmA2vZbUox1cxQSqL/XTNXIgJs2lMqvWesLgfM=,tag:tJeu5XbbWyEL1OM4PKuclQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
