apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:AUhJMARWyBCzqfq1CqJV1U9NHX9ZaK2oUPVoEBMTNSI=,iv:d8PU/AUl7jNPar25NjGf3w6dun+faQd5fpBqYhWblbM=,tag:oRifSXdpwdfrhSrSewYuPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age155j7rnhzl4qgq274jwrlyg4j6rfv38rhg7r850nmz27yxr3g2ctsjmq72t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYXFvNFRVUkttR1FZaHUx
            RXo5RDlqZnhnYjF3dU9nQ3FYRHpTMHYrUlMwCnU4TWl4M2pMK3h3V29xdG1mMk9m
            ajNFTFo3SmNmSmRFOVMvemdKak1wR3MKLS0tIHpWYTNGbXJNTEE1aG1SUXdxand4
            NHc0Q2pURFZaUWppWDVVQWQzb0FQNmMKgaeQo+DK07DUZ6/lHVCju6d/u6fZ3zmn
            ny7QvIxI4SVp7ifMNCqhNO8pChdkehaEUwQ3/Eb8beAEDr/po9XmaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-21T18:26:05Z"
    mac: ENC[AES256_GCM,data:94bGYuFOHKB1LYXSGe49iQzDUEz9VO38UvEOELhw1Nv97wq+CfXyBo/vdvI9kk09znWPLPB5MiovZ+peBaVmyuJQDb22h1KK2FRPb0OvLiLS0Q9AAQ/kLymxSkDGZMns5CE2TDE1foV+4AZc/Ezfgz0PwJkXCxymcTOmD0LoFyY=,iv:Xj7M0Yxc4wHtVir09nkGj/vomsCoW3QupuVhgWoQuT4=,tag:G97o13teh7R6MCKjb/IFdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
