apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:RIP8ZzLVGzCI5XBALF5c8YmtlDWwxlGy76FGp0ICeqE=,iv:lNRz+HRIgeNKdOTSjKS6nTXUk8pJlny33k3GxZlsM10=,tag:AxjF9qtrJn3F596cDrNsvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age155j7rnhzl4qgq274jwrlyg4j6rfv38rhg7r850nmz27yxr3g2ctsjmq72t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4L0R4TlZiNnZacHVLdWN5
            L3ZSQnFWR1ZMRjc1QUQycWtERlI2OStCeGprCmhaUTRaTjNpTFBOTjhidFh5WGxx
            WHpReFF0Njg1S0k0MG5OY2NKZGw5RmcKLS0tIG8vQmVNakdRR2laZTJXRjdMbnpu
            cG1VS2VVNmxBRzFIQ3ROdFkwTmZkWlUKTqJCfCrxQDGUg7nngcmwQP7IvA5Rf6wh
            u+k6VZZ/poODzDC40KfbXvw5NG0Dnxhk5ytwxBfIuy6aGC8tUhDwiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T18:18:56Z"
    mac: ENC[AES256_GCM,data:kqmRmA9mRdX8Kn+xxX9wziEjQwLcrAHt4C7Hf95upZh9PQid4OzfX4DmtYGoBVkYKSV93hoCZdMDJLU+T6ILDPCbceCJSko9r6PBqPonY+ZbLeiOrSdMZTwRZxJGprfxba7DFF5uDmHu5o3mEpzhkMrnFu0yNkCIEUyG2auzJzs=,iv:D72fNfhnAt3RUF0Xq62TNQauauhkeH73u9rIvArRJ/U=,tag:AOgt7ngxiqO0EOVin9eaQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
