apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:PWc5+Cyf2Jay1dYdqT9K94/BaaikFiA2fv005yUiqcjlOJh2uXbtIQ==,iv:2tpd3tdI6k98tMIXex0fGEpZMY1mBhYy3ZLPY/QsJ7U=,tag:CNrjaEJmFLP8U/us3v4hzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age155j7rnhzl4qgq274jwrlyg4j6rfv38rhg7r850nmz27yxr3g2ctsjmq72t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsU2tVVU5rU2tYTFFhM2Rn
            NEZwNzBqZjFKa2hTckNXQ2JZUWg1a3cybUZrCldRamp0a3krWVk1aEdEMEZXeVo2
            YWRpaVdNRG41dXVVYllzSzVIQmZNaG8KLS0tIFJrQzlCTkhFY1RxKzdOWkpublFa
            b2Vxd0ZOK2E5SmpmMFBscVErV2lLbjQKG0ffd+AZN1CeW7AlGZFSZrilo40UTY22
            XpQznOP9Cqg01Htlm3OrQuM1PkaNaA3v89AWCX8+7vviFFDcnF6vOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T18:18:55Z"
    mac: ENC[AES256_GCM,data:wBZ97k1HcUgSOgMRkL8AiSjU0cQ9v1qDlXwki4S3eV0y72bkhuKzAaEe+3ZnFh+6Xw/JWhI5pN0X7kNHTSwyz6uxwE4W04MUWUhxXhLs5CzWmPpI4dNP1ia30PInm5yaG5F92tLn3aQYJbP3LisMAlIaDN0jZHkfsMtJaIh1I6A=,iv:hyxDvWwp4UnO3ORWbzy0wvMZ/So4WHRNjm6ZxxejYvg=,tag:rVU93PPmzFZrXex68b98rA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
