apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:UJ7N7QQx/h2LHz5ZH1kqTKF2Pn5TMHHCYnFkbDL/Wq1el+04Gzuv6A==,iv:9Df07ImaS2Px7RH8rbs3viXq3URQbjkQHpLjwtzOZxM=,tag:g/Y51N0g98+cxpWFctyI1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age155j7rnhzl4qgq274jwrlyg4j6rfv38rhg7r850nmz27yxr3g2ctsjmq72t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbm55dFlNTUxXNnZ5Y0lL
            SUVDMTJ1b2tjb25mOTFFT0YzNnlFM3NMOUVFClFkZlV1QUN3NXhBZzFDUWI5RFVj
            VDFSR25hZUc5cTZhS3VicmNoNGUweW8KLS0tIERseWNkZzdUbjN4cWNQRHVGVkQr
            bE5RVmhEeTdSamM0TE1rMUcwbjVhOTgKNGUxnAe1vqSwEMCc4C1ld0+uQZoB6+DY
            cf5dpvTi/KQ+MttH2Wj4aQEwUzkFrQ6VVF4nwEeWAuidRDt6OnbzHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-21T18:26:05Z"
    mac: ENC[AES256_GCM,data:haBHBuXiHb5aCtXDVnCzUCE/o7UMBLfLaqOlDweE8aUSZBprg3GIzsPd+Muv7qGzYwyfjzL+Zj3BXJno0EfZt62JsTZhxIhWGP91rtcPwenHyyFfGgHFYgkJU9ZNIHG8UgfJyoRkJT0K4kFIq5jkTRy0IL690inbrs7c3FmTVO0=,iv:Uv18FG6eW1wqvBnQr9J9LNDdABoD1tQLdb4dixi6pLg=,tag:iCdBSigrEsQ93ZU9e/WE1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
