apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:r2cfPQmlwCzGIDhATwNR6djY59R/v2YkNIl5bcVlvToN2lBLa2K82g==,iv:vhweMO1igfd9akS/BfuAWG/YdM7fjLQ2FsE+Io74DbI=,tag:0QkruS0bDMRpWDWKkixDkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age155j7rnhzl4qgq274jwrlyg4j6rfv38rhg7r850nmz27yxr3g2ctsjmq72t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaGkxRnRUQ3hxVlRLRmlB
            cWl5MTQ3a1JleVJBMlkrQ0FVYm9LMnFBMXpJCjUwK3cvYTRKSEgvYmNRN2xDaHh6
            eTRFOHRmTUpVYWlBbkJUeTZzeFhXeWsKLS0tIDkyS052RXBzVDFhYjFOYW50alhl
            RmhDQVpQTkdlUFZHNm5wZVNCcWxicVUKsMePZhSbRZiAB/LJtxNgNdVDE7WVnxYU
            +wl0DjpY2aDCMQJPwM50MxJFOk/OTqGPU4yIg5ZD9dIEMtTm/ItszQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-25T13:15:15Z"
    mac: ENC[AES256_GCM,data:4KLlutD3p8R65Ql/3+sVFXe+Ps5D6PT/ticVOmTSaSPkAvdRncWJwAo8AbKx7zOinkiLSMOkrepPCghbRkiuStRwPR89AGfiPsDxphHVeX0ovmWrtTgDIm2+2ss3YNiYDgQpFLV8vRoyq3gYnFjGSclH8iKVylS6muCmvKHrQBc=,iv:ujxuUHfh3iF33D4xy5+kWYujHSadkW5D6cLlfsoshSc=,tag:9viVI8WEIEyUwavyJvvAuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
