apiVersion: v1
kind: Secret
metadata:
  name: onepassword-token
stringData:
  token: ENC[AES256_GCM,data:NBjqC9wD+t/DwZLqv+7ECD9JczK5nYkrrbNm5vYXxmxgV7o7sRUJcOLgJiCokdAufeaH9BiHyA6GQmA7Ezzw09DNRQCcLenkjOvOKFceXKFwCGsDvF6btMNdriS8nFE35/isUNVch9AxDUqm+0Oxl+ZJoZI17uqwBO0s28pvWReI8ajn4N3gVgowAqa4KG3swajEZ8BgtIgTIfPLzsVeP/x92lhUGHawosUOHpUb7FlWwpjOfAr5xILsc2toNU5LQAXje7AmPlwq9QLUGEnv3XX9raelG2UYYW3mzpxkdNErOLxgYxU5vLNt4NIVXAvLmcWRQ+Gy0ObM0zW/WruldoSaAxUwCwIQEdtu6/AC+jO547LsKqLw0BpA/23/SWfbV6UVSSuAmqJkLpP6QveToaV+Rkv7C1KFtDZAmg7lgDCaQjkkGyFyI5Zl+7TjT5OtI5S5NITuTaikZlImDKLejAKNVsQmD/m4wy1+S2mkENTjr8VlgrYhal5U8nKbMyz5xrOGVTPeYCQ1/qsvZEOs7vfyEVDbsPJgtoxx0Pic8qCuq+i9LfDPfM/YoP3knd5/CFDZin/zj/8ClY8pWS4lBytdsnUfzJ7rRk2w3vmu5Nm4um3qtpVb004eqVsYsgddwqg3HczaYPXPBWfIemOCzYBq+D3ZqPOfVGGo4uPiWnnC/fvEBm0MNZcyIWCjEKWSGxL1v0G9Wwc2NH1O1108NQ0OKbRalOv8h/kdUF6rUzKMQOcF7ctN9hqjM5M6y+iaiWhtD3LwQP6qvjQ8gclNZBE5Onoch/R1hjKKL+P1p+aZwyIlI3xsmDXBPOCS1m5AX5Ns9l1ipKfjALWhzqtAZJEsNbdawo6GfWGYKz8WAzDq85GYdemjzr0fBlffDF3FqMUR9QJL093lEIRCpMpNGIIolCp7ge8XAENmmvxQBK+v6aPlYGJ9u69HzQM461aVcR/HCSgZ+nmOAo+WuX4L21sDeYaWw1GwmV7r2NKyESMwQPLKL6ZLOJOiY+6W88RZNGKmgspxx0Xd1jl1Idy6KD61TkEZaFic9y1LZL9IOMcB1MOi63P2piMzIfBbkCUtBxXAgEAUUKdBwn8N4R6Z9q73U1RNfnOtq19Y85FwLcVrJY9h,iv:hpauFiOoQxyJ6UUhkKs6VbjBg62/105kLErrxa24Q2Y=,tag:j9grWSPTilCAVa428KgMCw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwa002Z1picVJpTUF6b25S
        cTJ5TUZUUmxCVktnMktWanF3OE5uaGRnYmdJCnQvWVl1TjZhRUlpbWl0cGErM0dw
        RkdxMnM5ZjY1cEpMSVE4NHkwcWQyRkkKLS0tIEk1aE9WaGMyTlo2WE1tcWZUbVZk
        NTNwS0g4bEdFS0k4aGpMVW9OT25IQnMKs+xB8vCw3/iBqMuukvqrS+xa36/EZK+3
        BdRLV8DL/k6ax/wvnWIvK9/Iij3Y+DHJ1zcBnqBADhYuBu6f6Y7l+Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1a8vdr200sct5atefmhhaqnxac7us6dd50hwg8e3e85mcmcd4sdgqnljfjp
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-02T18:52:54Z"
  mac: ENC[AES256_GCM,data:V8u/ru1BAXjjo57vb7kQRG1pwb+R1iN0wkTCpC+1SrQ8Z4U0G6CFd86rJq/ZX1ktaMyf7Xwx8E3kYplzkYkCHk6Lc8kEaMk+hf+pXzCGbrfByT3ESV8Gda6fHcZmdE5WIHZDhTQRJnL23ekWy/BHqJbl5uZVtqXgboEoWssed+4=,iv:eGC/4HQg/fYAaTkqflNJQSUZdQ4apqtiggR3/R18YvU=,tag:IUAmEHqO2fmAXP8xoscrow==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
